### ISSUE TITLE
Vandermonde performance

### ISSUE THREAD

**Issue by synapticarbors** [weijianzhang/MatrixDepot.jl#2]
While performance might not be the primary goal of this package, I thought I'd mention that while trying to get a handle on Julia's performance, I benchmarked a number of Vandermonde implementations, including the one in MatrixDepot against numpy's `np.vander`. The results are here:

http://nbviewer.ipython.org/gist/synapticarbors/26910166ab775c04c47b

I'd be happy to submit a PR implementing `vander3` if you're interested.

**Comment by weijianzhang** [comment]
That's great stuff. Thanks. I am always interested in improving the performance.
Please submit a pull request.
