### ISSUE TITLE
Generic infrastructure

### ISSUE THREAD

**Issue by jpfairbanks** [weijianzhang/MatrixDepot.jl#9]
I was about to ask about having graph datasets. They are mostly matrices but the edges might be ordered and have other metadata on them. What part of the infrastructure in this project is reusable and can be shared between RDatasets and MatrixDepot and a hypothetical GraphsDepot? You have a some capacity for making personal collections, labeling, indexing, querying, and IO. Also there are features for generators and static matrices.

**Comment by weijianzhang** [comment]
Hi @jpfairbanks,

MatrixDepot use ``Dict`` to store and display matrix information. I think RDatasets use ``DataFrame`` to do similar tasks, but I am not sure about that.  

I guess the way to download data from web is reusable?
https://github.com/weijianzhang/MatrixDepot.jl/blob/master/src/download.jl

Just for reference, graph matrices from Stanford Large Network Dataset Collection are also available from UF sparse matrix collection (http://www.cise.ufl.edu/research/sparse/matrices/SNAP/) so you can download them to MatrixDepot with ``MatrixDepot.get``. 

Best,
Weijian
